#!/usr/bin/env bash
# Usage: ./1-world_wide_web <domain> <subdomain>
# Display information about subdomains.

domain_information () {
    local result=$(dig +short "$2"."$1" | tail -n1)
    if [ -z "$result" ]; then
        echo "Error: Subdomain $2 not found for domain $1"
    else
        local record_type=$(dig +short "$2"."$1" | head -n1 | awk -F' ' '{print $4}')
        echo "The subdomain $2 is a $record_type record and points to $result"
    fi
}

if [ "$#" -lt 1 ] || [ "$#" -gt 2 ]; then
  echo "Usage: $0 <domain> [subdomain]"
  exit 1
fi

if [ "$#" -eq 1 ]; then
  domain_information "$1" "www"
  domain_information "$1" "lb-01"
  domain_information "$1" "web-01"
  domain_information "$1" "web-02"
elif [ "$#" -eq 2 ]; then
  domain_information "$1" "$2"
fi
